daniel-hauser/moneyman

- README.md
There's actually both sheet ID and spreadsheet ID, so removing confusion
> sheet -> spreadsheet

- patches/israeli-bank-scrapers+3.7.0.patch
When scraping cal transactions, sometimes I get a "could not find 'init' data in session storage" error.
This patch allows a longer second attempt
> Allow more time for cal init

- .vscode/launch.json
- src/notifier.ts
- tsconfig.json
When editing a message without changing the text telegram throwes an error:
```
Error: 400: Bad Request: message is not modified: specified new message content and reply markup are exactly the same as a current content and reply markup of the message
```
This error is not really an error, so no need to report it
> Ignore "Bad Request: message is not modified"

- .github/workflows/verify-build.yml
- jest.config.js
- package-lock.json
- package.json
- src/storage/index.ts
- src/storage/utils.test.ts
- src/storage/utils.ts
This PR removes null/undefined from the hash as well as adds test for the fix.
The new cal scraper added in https://github.com/eshaham/israeli-bank-scrapers/pull/767 has no memo field (`== undefined`).
This caused duplications with transactions scraped **before** cal moved to the new website (using the previous scraper).
After merging, all transactions scraped **after** the cal scraper was fixed will now have duplications.
Fixes #132
> Remove 'undefined' from the hash

- src/storage/json.ts
When using `LocalJsonStorage` on windows the following error is thrown:
```
ENOENT: no such file or directory, open '<cwd>\output\2023-11-10T21:00:00.000Z.json'
```
This is caused by the `:` in the ISO string used as the file name.
Replacing `:` with `_` 
----
Fixes #182
> [JSON Storage] Fix exported file name on windows

- patches/israeli-bank-scrapers+4.1.0+001+initial.patch
The current implementation of the scraper takes the amount from the `customerPrice` field returned from the behatsdaa api result, which has the charged amount as a positive number.
Patched to fix it until https://github.com/eshaham/israeli-bank-scrapers/pull/819 is merged
> Fix behatsdaa amount to be negative

- src/__snapshots__/messages.test.ts.snap
- src/messages.test.ts
- src/messages.ts
In the message sent, the originalAmount is sent instead of the chargedAmount.
This will hold the incorrect result in case of installments
> Fix: message has the whole installments amount and not charged amount

- .github/workflows/build.yml
- .github/workflows/scrape.yml
Currently, the user's name is used as the repository name. This will fail the build in cases where the GitHub user name is not lowercase.
This PR adds a normalization step that will use the lowercase version of the user's name
Fixes #220
> Fix: Allow usage for users with uppercase characters in the username

- .github/workflows/scrape.yml
@daniel-hauser PTAL.
I found that the Scrape Action lack the env vars required to export to YNAB.
This PR fix that.
BTW.... the `DEBUG` is hardcoded to ""... this is intentional?
> fix: add missing env vars for GitHub Scrape action

- README.md
- src/notifier.ts
* [`src/notifier.ts`](diffhunk://#diff-5f8382d927f65fd353aa13dd3f49dcdd7c6c51515ab46eb03fccd081a45997f7R19-R25): In the `send` function, a check has been added to ensure that the message length does not exceed 4096 characters. If it does, the message is truncated and a notification about the truncation is sent.
This is to prevent https://github.com/telegraf/telegraf/discussions/1785
* [`src/notifier.ts`](diffhunk://#diff-5f8382d927f65fd353aa13dd3f49dcdd7c6c51515ab46eb03fccd081a45997f7L68-R79): In the `sendDeprecationMessage` function, the `HIDDEN_DEPRECATIONS` environment variable is now used to initialize the `sentDeprecationMessages` set, effectively hiding the specified deprecation messages. Also, a log message has been added to log the hidden deprecations.
> Small fixes

- src/__snapshots__/messages.test.ts.snap
- src/index.ts
- src/messages.test.ts
- src/messages.ts
In some cases, the status message s too long, resulting with an error/truncation when sending.
This change will split the message, resulting with a lower chance of errors
> Split status messages

- Dockerfile
Moving to the official puppeteer docker image (puppeteer has no official support for alpine,  and now fails to load chrome properly in alpine)
Fixes #313
> Use the official puppeteer image

- patches/israeli-bank-scrapers+5.1.1.patch
Transactions in isracard has the wrong originalCurrency. the correct mapping of the currencies should be:
- `originalCurrency` = `currentPaymentCurrency`
- `chargedCurrency` = `currencyId`
This PR patches until https://github.com/eshaham/israeli-bank-scrapers/pull/871 is merged
> fix(isracard): PATCH use the correct value for originalCurrency

- .github/workflows/verify-build.yml
- package-lock.json
- package.json
This pull request updates the Node.js version used in the project configuration files to ensure compatibility with newer Node.js versions. The most important changes include updating the Node.js version in the GitHub Actions workflow and the `package.json` file.
* [`.github/workflows/verify-build.yml`](diffhunk://#diff-936fbed6fe307d4f159b5e5b3901d9d4ba5f7ca810a6d185e8c965ad26adf9f0L15-R15): Updated the Node.js version in the matrix strategy from `16.x` to `20` and `latest`.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L8-R8): Changed the required Node.js version in the `engines` field from `>16` to `>=20`.
> chore: Update Node.js version requirement to >=20

- jest.config.js
- src/config.ts
- src/data/index.ts
- src/messages.test.ts
- src/messages.ts
- src/notifier.ts
- src/saveStats.ts
- src/storage/azure-data-explorer.ts
- src/storage/utils.test.ts
- src/storage/utils.ts
- src/types.ts
- src/utils/currency.test.ts
After merging #341 the scraper failed on runtime with the following error:
```
node:internal/modules/esm/resolve:265
throw new ERR_MODULE_NOT_FOUND(
^
Error ***ERR_MODULE_NOT_FOUND***: Cannot find module '/app/dst/utils/currency' imported from /app/dst/messages.js
at finalizeResolution (node:internal/modules/esm/resolve:265:11)
at moduleResolve (node:internal/modules/esm/resolve:933:10)
at defaultResolve (node:internal/modules/esm/resolve:1169:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:540:12)
at ModuleLoader.resolve (node:internal/modules/esm/loader:509:25)
at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:[38](https://github.com/daniel-hauser/moneyman/actions/runs/10759210526/job/29835599792#step:4:38))
at ModuleWrap.<anonymous> …
```
> fix: runtime import error import error

- src/storage/sheets.ts
This pull request includes a change in the `transactionRow` function in the `src/storage/sheets.ts` file to handle the `chargedCurrency` more robustly by using the `originalCurrency` if `chargedCurrency` is not available.
Improvements to currency handling:
* [`src/storage/sheets.ts`](diffhunk://#diff-7b5df94ab18466419342c19861d0076aa3fe1f3cc917d0fda17aaa7ddfe33d78L51-R52): Modified the `transactionRow` function to use `normalizeCurrency(tx.chargedCurrency) || normalizeCurrency(tx.originalCurrency)` for the `chargedCurrency` field, assuming the transaction is not pending.
> feat: `chargedCurrency` now defaults to `originalCurrency`

- src/__snapshots__/messages.test.ts.snap
- src/messages.test.ts
- src/saveStats.ts
- src/storage/index.ts
This pull request includes changes to improve the performance of saving results and enhance the logging details. The most important changes include adding parallel processing for saving transactions, modifying the logging mechanism, and updating the `statsString` function to include the duration of the save operation.
Performance improvements:
* [`src/storage/index.ts`](diffhunk://#diff-189df448d4739484d3f18a1acd3d9f4b947564f111c3fb4ef7c14c284ec4c430L37-R63): Introduced parallel processing for saving transactions to different storages using the `parallel` function from the `async` library.
Logging enhancements:
* [`src/storage/index.ts`](diffhunk://#diff-189df448d4739484d3f18a1acd3d9f4b947564f111c3fb4ef7c14c284ec4c430R13-R15): Changed the logger initialization to use …
> feat: parallelize saving to storages

- README.md
- src/bot/storage/web-post.ts
Adding the ability to add Authorization header to the POST request on web-post module
> feat: adding authorization header to web-post

- package-lock.json
- package.json
- src/scraper/scrape.test.ts
- Introduce `jest-mock-extended` for mocking in tests
- add unit tests for the `getAccountTransactions` function to ensure the browserContext is properly used
> Add unit tests for getAccountTransactions

- .github/workflows/build.yml
With this project, it is highly recommended to review the code I'm running.
For that, I want to be able to run a specific version of the project, and not automaticlly receive the latest version, which, in case of bad thing happend, will stole my passwords.
With this change, each docker image will be tagged with the git commit hash, and we will be able to consume it even if the latest is another image.
> ci: add tag of short-sha to docker image

- .github/workflows/scrape.yml
- README.md
- patches/israeli-bank-scrapers+5.4.6.patch
- src/index.ts
- src/runnerMetadata.ts
- src/scraper/index.ts
- src/security/__snapshots__/domains.test.ts.snap
- src/security/domainRules.test.ts
- src/security/domainRules.ts
- src/security/domains.test.ts
- src/security/domains.ts
- src/types.ts
- src/utils/collections.ts
- src/utils/logger.ts
This pull request introduces a new feature for managing domain access rules for scrapers, including updates to the workflow configuration, documentation, and the addition of new domain rule logic and tests.
* [`.github/workflows/scrape.yml`](diffhunk://#diff-5f72821278fe20f161d8ff66811c979351ef53d21ea57391f3087ef336726bc1R75-R76): Added `FIREWALL_SETTINGS` and `BLOCK_BY_DEFAULT` environment variables to the workflow configuration. [[1]](diffhunk://#diff-5f72821278fe20f161d8ff66811c979351ef53d21ea57391f3087ef336726bc1R75-R76) [[2]](diffhunk://#diff-5f72821278fe20f161d8ff66811c979351ef53d21ea57391f3087ef336726bc1R107-R108)
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L114-R141): Updated the documentation to include details on configuring …
> feat: allow to block puppeteer requests
